#!/bin/bash

export VENDOR=zte
export DEVICE=nx510j

OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l ../$DEVICE/proprietary-files.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' ../$DEVICE/proprietary-files.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' ../$DEVICE/proprietary-files.txt`; do
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  # Split the file from the destination (format is "file[:destination]")
  OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
  if [[ ! "$FILE" =~ ^-.* ]]; then
    FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
    DEST=${PARSING_ARRAY[1]}
    if [ -n "$DEST" ]; then
      FILE=$DEST
    fi
    echo "    $OUTDIR/proprietary/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
  fi
done

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk
# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
PRODUCT_PACKAGES += \\
    TimeService \\
    libTimeService \\
    libtime_genoff \\
    libmdmdetect \\
    libFlacSwDec

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
EOF

(cat << EOF) > ../../../$OUTDIR/Android.mk
# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

LOCAL_PATH := \$(call my-dir)

ifneq (\$(filter nx510j,\$(TARGET_DEVICE)),)

include \$(CLEAR_VARS)
LOCAL_MODULE        := com.qualcomm.location
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := platform
LOCAL_SRC_FILES     := proprietary/app/com.qualcomm.location/com.qualcomm.location.apk
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := com.qualcomm.services.location
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := platform
LOCAL_SRC_FILES     := proprietary/app/com.qualcomm.services.location/com.qualcomm.services.location.apk
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := TimeService
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := platform
LOCAL_SRC_FILES     := proprietary/app/TimeService/TimeService.apk
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := qcrilmsgtunnel
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := platform
LOCAL_SRC_FILES     := proprietary/app/qcrilmsgtunnel/qcrilmsgtunnel.apk
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := shutdownlistener
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := platform
LOCAL_SRC_FILES     := proprietary/app/shutdownlistener/shutdownlistener.apk
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := qcnvitems
LOCAL_MODULE_CLASS  := JAVA_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := PRESIGNED
LOCAL_SRC_FILES     := proprietary/framework/qcnvitems.jar
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := qcrilhook
LOCAL_MODULE_CLASS  := JAVA_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := PRESIGNED
LOCAL_SRC_FILES     := proprietary/framework/qcrilhook.jar
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libFlacSwDec
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 32
LOCAL_SRC_FILES     := proprietary/vendor/lib/libFlacSwDec.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libFlacSwDec
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib64
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 64
LOCAL_SRC_FILES     := proprietary/vendor/lib64/libFlacSwDec.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libmdmdetect
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 32
LOCAL_SRC_FILES     := proprietary/vendor/lib/libmdmdetect.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libmdmdetect
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib64
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 64
LOCAL_SRC_FILES     := proprietary/vendor/lib64/libmdmdetect.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libtime_genoff
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 32
LOCAL_SRC_FILES     := proprietary/vendor/lib/libtime_genoff.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libtime_genoff
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib64
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 64
LOCAL_SRC_FILES     := proprietary/vendor/lib64/libtime_genoff.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libTimeService
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 32
LOCAL_SRC_FILES     := proprietary/vendor/lib/libTimeService.so
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE        := libTimeService
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_OWNER  := qcom
LOCAL_MODULE_PATH   := \$(PRODUCT_OUT)/system/vendor/lib64
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS   := optional
LOCAL_MULTILIB      := 64
LOCAL_SRC_FILES     := proprietary/vendor/lib64/libTimeService.so
include \$(BUILD_PREBUILT)

\$(shell mkdir -p \$(PRODUCT_OUT)/system/vendor/lib/egl && pushd \$(PRODUCT_OUT)/system/vendor/lib > /dev/null && ln -s egl/libEGL_adreno.so libEGL_adreno.so && popd > /dev/null)
\$(shell mkdir -p \$(PRODUCT_OUT)/system/vendor/lib64/egl && pushd \$(PRODUCT_OUT)/system/vendor/lib64 > /dev/null && ln -s egl/libEGL_adreno.so libEGL_adreno.so && popd > /dev/null)

endif

EOF
